name: Analisis SonarCloud

on: [push]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Instalar Dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest pytest-cov

      - name: Instalar dependencias del sistema
        run: |
          sudo apt-get install -y curl unzip

      - name: Instalar Sonar Scanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner.zip
          mv sonar-scanner-4.8.0.2856-linux sonar-scanner
          echo "$(pwd)/sonar-scanner/bin" >> $GITHUB_PATH

      - name: Ejecutar escaner SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "https://sonarcloud.io"
          JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17
        run: |
          sonar-scanner/bin/sonar-scanner \
            -Dsonar.projectKey=app-ejemplo \
            -Dsonar.organization=alejandrolmeida \
            -Dsonar.sources=. \
            -Dsonar.java.binaries=. \
            -Dsonar.java.libraries=lib \
            -Dsonar.java.source=17 \
            -Dsonar.java.target=17 \
            -Dsonar.exclusions=**/node_modules/**,**/target/**,**/build/**,**/dist/**,**/coverage/**,**/lib/**,**/sonar-scanner/**,**/sonar-scanner.zip