name: Analisis SonarCloud 

on: [push]
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Instalar Dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest pytest-cov
      - name: Ejecutar escaner SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "https://sonarcloud.io"
        run: |
          sonar-scanner
      - name: Check SonarCloud Quality 
        run: |
          curl -u ${{ secrets.SONAR_TOKEN }}: \
          "https://sonarcloud.io/api/qualitygates/project_status?projectKey=Test-Project" \
          | jq -r '.projectStatus.status' > status.txt
      - name: Send notification if Quality Gate fails
        if: failure()
        run: |
          status=$(cat status.txt)
          if [ "$status" != "OK" ]; then
            echo "El proyecto no pasó la evaluación de SonarCloud: $status"
          fi